apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - wordpress-vpc.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml
secretGenerator:
  - name: wordpress
    literals:
      - db.host=mysql:3306
      - db.password=SomeRandomPassword&Q^@&$
namespace: wordpress
